#!/bin/bash

# Küsib kasutajalt arvu ning väljastab
# kas see on algarv või mitte
printf 'Sisesta suvaline arv: ' arv
read arv

if [ $arv -le 1 ];then
    printf "%s $arv - ei ole algarv\n"
else
    jagaja=2
    jaak=$(($arv % $jagaja))
    while [ $jaak -ne 0 ]
    do
        jagaja=$(($jagaja + 1))
        jaak=$(($arv % $jagaja))
    done
    if [ $jagaja -eq $arv ];then
        printf "$arv - on algarv\n"
    else
        printf "%s $arv - ei ole algarv\n"
    fi
fi

