#!/bin/bash

# Lisab mitu muutujat kokku üheks lauseks ja väljastab selle
aasta=2016
president="Kersti Kaljulaid"
lause_keskosa=". aastal valiti Eesti presidendiks "

lause=$aasta$lause_keskosa$president
echo $lause
