#!/bin/bash

# Küsib kasutajalt kellaega ning tervitab
# vastavalt sisestatud kellajale
read -p "Sisesta aja väärtus: " aeg

if [ $aeg -ge 6 -a $aeg -lt 12 ];then
    printf "Tere hommikust!\n"
elif [ $aeg -ge 12 -a $aeg -lt 18 ];then
    printf "Tere päevast!\n"
elif [ $aeg -ge 18 -a $aeg -lt 22 ];then
    printf "Tere õhtust!\n"
elif [ $aeg -ge 22 -a $aeg -lt 24 ] || [ $aeg -ge 0 -a $aeg -lt 6 ];then
    printf "Head ööd!\n"
else
    printf "Vigane sisend\n"
fi
