#!/bin/bash

# Kasutab süsteemi kellaega ning
# tervitab kasutajat tema nimega
aeg=$(date +%H)
nimi=$(whoami)
nimi=${nimi^}

if [ $aeg -ge 6 -a $aeg -lt 12 ];then
    printf "Tere hommikust, $nimi!\n"
elif [ $aeg -ge 12 -a $aeg -lt 18 ];then
    printf "Tere päevast $nimi!\n"
elif [ $aeg -ge 18 -a $aeg -lt 22 ];then
    printf "Tere õhtust $nimi!\n"
elif [ $aeg -ge 22 -a $aeg -lt 24 ] || [ $aeg -ge 0 -a $aeg -lt 6 ];then
    printf "Head ööd $nimi!\n"
else
    printf "Vigane sisend\n"
fi
